name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Show Files
        run: |
          pwd
          ls -R

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Frontend
        run: |
          cd frontend
          docker build -t test-frontend .

      - name: Build Backend
        run: |
          cd backend
          docker build -t test-backend .